# Generic single-database configuration file for Alembic.

[alembic]
# path to migration scripts
script_location = app/alembic

# Template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# Useful when running alembic without installing package
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
timezone = UTC

# version path separator; As mentioned above, this is the character used to split
# version_path_separator is os-dependent. Valid values are:
#
# os (default) - use os.pathsep. e.g. ';' on Windows, ':' on Unix/Mac
# ; - use the semicolon as separator
# : - use the colon as separator
# space - use the space as separator
version_path_separator = os  # Use os.pathsep. Default configuration used for new projects.

# Set the output encoding used when revision files are written from script.py.mako
# output_encoding = utf-8

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
