"""app/schemas/admin — Admin panel Pydantic v2 sxemalari."""
from app.schemas.admin.common import ErrorResponse, Page, PageMeta
from app.schemas.admin.auth import (
    AdminProfile,
    OtpRequestIn,
    OtpRequestOut,
    OtpVerifyIn,
    RefreshIn,
    TelegramLoginIn,
    TokenPair,
)
from app.schemas.admin.dashboard import (
    DashboardOverview,
    FailureBreakdown,
    KpiCards,
    PlanUsage,
    QuestionDistributionItem,
    ScanPoint,
    SystemStatus,
    TeacherActivityPoint,
    TopTeacher,
)
from app.schemas.admin.users import (
    BlockUserIn,
    ChangeAdminRoleIn,
    TeacherDetail,
    TeacherListItem,
    TeacherStats,
)
from app.schemas.admin.explorer import (
    GroupDetail,
    GroupListItem,
    StudentListItem,
    StudentResultItem,
    TestDetail,
    TestListItem,
)
from app.schemas.admin.scans import (
    BubbleCell,
    OmrInspectorOut,
    OverrideAnswersIn,
    ScanListItem,
    ScanQuestionRow,
)
from app.schemas.admin.subscriptions import (
    AssignPlanIn,
    GrantCreditsIn,
    PlanIn,
    PlanOut,
    SubscriptionOut,
    SubscriptionRow,
)
from app.schemas.admin.broadcasts import (
    BroadcastCreateIn,
    BroadcastDetail,
    BroadcastListItem,
    BroadcastPreviewOut,
    RecipientRow,
)
from app.schemas.admin.audit import AuditLogItem

__all__ = [
    "ErrorResponse",
    "Page",
    "PageMeta",
    "AdminProfile",
    "OtpRequestIn",
    "OtpRequestOut",
    "OtpVerifyIn",
    "RefreshIn",
    "TelegramLoginIn",
    "TokenPair",
    "DashboardOverview",
    "FailureBreakdown",
    "KpiCards",
    "PlanUsage",
    "QuestionDistributionItem",
    "ScanPoint",
    "SystemStatus",
    "TeacherActivityPoint",
    "TopTeacher",
    "BlockUserIn",
    "ChangeAdminRoleIn",
    "TeacherDetail",
    "TeacherListItem",
    "TeacherStats",
    "GroupDetail",
    "GroupListItem",
    "StudentListItem",
    "StudentResultItem",
    "TestDetail",
    "TestListItem",
    "BubbleCell",
    "OmrInspectorOut",
    "OverrideAnswersIn",
    "ScanListItem",
    "ScanQuestionRow",
    "AssignPlanIn",
    "GrantCreditsIn",
    "PlanIn",
    "PlanOut",
    "SubscriptionOut",
    "SubscriptionRow",
    "BroadcastCreateIn",
    "BroadcastDetail",
    "BroadcastListItem",
    "BroadcastPreviewOut",
    "RecipientRow",
    "AuditLogItem",
]
